// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// getChangePoints
List getChangePoints(Rcpp::NumericMatrix data, double penalty, std::string method, std::string type, std::string intersection, std::string exclusion, bool showNbCands);
RcppExport SEXP _GeomFPOP_getChangePoints(SEXP dataSEXP, SEXP penaltySEXP, SEXP methodSEXP, SEXP typeSEXP, SEXP intersectionSEXP, SEXP exclusionSEXP, SEXP showNbCandsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type penalty(penaltySEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< std::string >::type intersection(intersectionSEXP);
    Rcpp::traits::input_parameter< std::string >::type exclusion(exclusionSEXP);
    Rcpp::traits::input_parameter< bool >::type showNbCands(showNbCandsSEXP);
    rcpp_result_gen = Rcpp::wrap(getChangePoints(data, penalty, method, type, intersection, exclusion, showNbCands));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GeomFPOP_getChangePoints", (DL_FUNC) &_GeomFPOP_getChangePoints, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_GeomFPOP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
